### ISSUE TITLE
Add a route for security section of configuration

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/key#33]

**Comment by rlhawk** [comment]
It appears that if multiple modules define the same path for the configuration category, multiple sections are created.

![image](https://cloud.githubusercontent.com/assets/851084/9179412/4162f1e8-3f51-11e5-8ac7-2ac6751c4e1d.png)

**Comment by nerdstein** [comment]
@pbull - what did we come up with for this with PP?

**Comment by pbull** [comment]
@nerdstein Interesting, I didn't observe that behavior with the latest D8 head yesterday, I added the route with the same path and controller to two modules and they both appeared under the same section.

@rlhawk do you have a link to the Keys repo you were using when you experienced this, I wonder what is different between the two routes?

**Comment by rlhawk** [comment]
I'm using my Key repo at https://github.com/rlhawk/key

I'm also using the latest D8 beta (14), so perhaps this issue has been addressed in core since then.

**Comment by rlhawk** [comment]
I'm still seeing this behavior with the latest D8 head. The relevant routes look like this:

```
password_policy.admin_index:
  path: '/admin/config/security'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Security'
  requirements:
    _permission: 'access administration pages'
```

```
key.admin_index:
  path: '/admin/config/security'
  defaults:
    _content: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Security'
  requirements:
    _permission: 'access administration pages'
```

I tried changing _content to _controller in key.admin_index, but it didn't make a difference.

**Comment by rlhawk** [comment]
The menu entries look like this:

```
key.admin_index:
  title: Security
  description: 'Configuring security settings'
  parent: system.admin_config
  route_name: key.admin_index
```

```
password_policy.admin_index:
  title: Security
  description: 'Configuring security settings'
  parent: system.admin_config
  route_name: password_policy.admin_index
```
